config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/posts/import' => 'posts#import'
  post '/posts/import' => 'posts#upload'
  post '/posts/set_dates' => 'posts#set_dates'
  resources :posts
  resources :users

  get 'auth/:provider/callback', to: 'users#auth'

  authenticated :user do
    root to: "posts#index"
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/registrations#new", as: :unauthenticated_root
    end
  end

  get '/settings' => 'users#settings'
  post '/settings/publish_token' => 'users#publish_token'

  get '/archive' => 'posts#archive'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => { :original => '1000>', :thumb => '100x100'}
  validates_attachment_content_type :image, :content_type => ["image/jpg","image/jpeg","image/png","image/gif",]
  belongs_to :user

  def self.set_dates(dates, current_user)

    all_posts = Post.where(:user_id => current_user).order('id ASC')
    facebook_next_date = DateTime.parse(dates[:facebook_publish_date]).to_i + dates[:facebook_publish_time].to_i * 60 * 60
    twitter_next_date = DateTime.parse(dates[:twitter_publish_date]).to_i + dates[:twitter_publish_time].to_i * 60 * 60

    all_posts.each do |p|
      if p.facebook?
        facebook_next_date += dates[:facebook_interval].to_i * 60 * 60
        p.facebook_publish_date = Time.at(facebook_next_date).to_datetime
        p.save
      end

      if p.twitter?
        twitter_next_date += dates[:twitter_interval].to_i * 60 * 60
        p.twitter_publish_date = Time.at(twitter_next_date).to_datetime
        p.save
      end

    end
  end

  def self.posting
    posts = Post.where("published = false AND (facebook_publish_date <= CURRENT_TIMESTAMP OR twitter_publish_date <= CURRENT_TIMESTAMP)")
    posts.each do |p|
      if p.twitter?
        unless p.twitter_publish_date.blank?
            client = Twitter::REST::Client.new do |config|
            config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
            config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
            config.access_token = p.user.twitter_oauth_token
            config.access_token_secret = p.user.twitter_oauth_secret
            end
          if p.image?
            client.update_with_media(p.text, File.new(p.image.path))
          else
            client.update(p.text)
          end
        end
      end

      if p.facebook?
        unless p.facebook_publish_date.blank?
          @graph = Koala::Facebook::API.new(p.user.facebook_publish_token)
          if p.image?
            @graph.put_picture(File.new(p.image.path), {:message => p.text})
          else
            post_info = @graph.put_wall_post(p.text)
          end
      end
      end

      p.published = true
      p.save
  end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth,current_user)
      user = User.find(current_user.id)
      case auth.provider
        when 'twitter'
          user.twitter_oauth_token = auth.credentials.token
          user.twitter_oauth_secret = auth.credentials.secret
        when 'facebook'
          user.facebook_oauth_token = auth.credentials.token
      end

      user.save!

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.where(user_id: current_user.id, published: false).order('id ASC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def import

  end

  def archive
    @posts = Post.where(user_id: current_user.id, published: true).order('id ASC')
  end

  def set_dates
    Post.set_dates(params[:dates], current_user.id)

    redirect_to posts_path
  end

  def upload
    uploaded_io = params[:post][:excell]

    if uploaded_io
      new_name = Time.now.to_i.to_s
      File.open("/tmp/"+uploaded_io.original_filename, "wb") do |file|
        file.write(uploaded_io.read)
      end

      xlsx = Roo::Excelx.new("/tmp/"+uploaded_io.original_filename)

      posts = []
      (1..xlsx.last_row).each do |i|
        posts << {text: xlsx.row(i)[0].to_s}
      end

      Post.create!(posts) do |p|
        p.facebook = true
        p.twitter = true
        p.published = false
        p.user_id = current_user.id
      end

      flash[:notice] = "Upload Successful"
    end

    redirect_to posts_import_path
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:text, :publish_date, :image, :twitter, :facebook, :facebook_publish_date, :twitter_publish_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:settings, :update, :publish_token]
  before_filter :authenticate_user!, only: [:show, :edit, :update, :destroy, :settings]

  def update
    if @user.update(user_params)

    end

    redirect_to settings_path
  end

  def auth
    User.from_omniauth(env["omniauth.auth"],current_user)

    redirect_to root_path
  end

  def settings
    @user_facebook_oauth = @user.facebook_oauth_token
  end

  def publish_token

    if params[:facebook] == "profile"
      @user.facebook_publish_token = @user.facebook_oauth_token
      @user.save
    else
      @user.facebook_publish_token = params[:facebook]
      @user.save
    end

    redirect_to settings_path
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:full_name, :company_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autoposting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <% if user_signed_in? %>
    <li>
      <%= link_to('Log out', destroy_user_session_path, :method => :delete) %>
    </li>
  <% else %>
    <li>
      <%= link_to('Sign up', new_user_registration_path)  %>
      <%= link_to('Sign in', new_user_session_path)  %>
    </li>
  <% end %>
</div>
<ul>
  <li><%= link_to "Upload Sheet", posts_import_path %> </li>
  <li><%= link_to "Schedule", posts_path %> </li>
  <li><%= link_to "Settings", settings_path %> </li>
  <li><%= link_to "Archive", archive_path %> </li>
</ul>
<div><%= flash[:notice] if flash[:notice] %></div>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .actions
    .row
      = f.label :text
      = f.text_area :text
    .row
      = f.label :image
      = f.file_field :image
    .row
      = f.label :facebook
      = f.check_box :facebook
    .row
      = f.label :twitter
      = f.check_box :twitter
    .row
      = f.label :facebook_publish_date
      = f.text_field :facebook_publish_date
    .row
      = f.label :twitter_publish_date
      = f.text_field :twitter_publish_date
    = f.submit 'Save'

app/views/posts/_set_dates.html.haml
- hours = [["1 hour",1],["2 hours",2],["3 hours",3],["4 hours",4],["5 hours",5],["6 hours",6],["7 hours",7],["8 hours",8],["9 hours",9],["10 hours",10],["11 hours",11],["12 hours",12],["13 hours",13],["14 hours",14],["15 hours",15],["16 hours",16],["17 hours",17],["18 hours",18],["19 hours",19],["20 hours",20],["21 hours",21],["22 hours",22],["23 hours",23],["24 hours",24]]
- time = [["00:00", 0],["01:00", 1],["02:00", 2],["03:00", 3],["04:00", 4],["05:00", 5],["06:00", 6],["07:00", 7],["08:00", 8],["09:00", 9],["10:00", 10],["11:00", 11],["12:00", 12],["13:00", 13],["14:00", 14],["15:00", 15],["16:00", 16],["17:00", 17],["18:00", 18],["19:00", 19],["20:00", 20],["21:00", 21],["22:00", 22],["23:00", 23]]
= form_tag(posts_set_dates_path) do
  .row
    %span Schedule a Facebook Post every
    = select_tag("dates[facebook_interval]", options_for_select(hours))
    %span starting
    = text_field(:dates, :facebook_publish_date)
    %span at
    = select_tag("dates[facebook_publish_time]", options_for_select(time))
  .row
    %span Schedule a Tweet every
    = select_tag("dates[twitter_interval]", options_for_select(hours))
    %span starting
    = text_field(:dates, :twitter_publish_date)
    %span at
    = select_tag("dates[twitter_publish_time]", options_for_select(time))
  = submit_tag "Schedule"

app/views/posts/archive.html.haml
%h1 Bulk Scheduler

%table
  %thead
    %tr
      %th
      %th
      %th
      %th
      %th
      %th
      %th
  %tbody
    - i = 0
    - @posts.each do |post|
      - i += 1
      %tr
        %td= i
        %td= post.text
        %td= image_tag post.image(:thumb) unless post.image.blank?
        %td
        %td
          - if post.facebook?
            = 'Facebook'
            %br
            = post.facebook_publish_date.strftime("%B %e, %Y %l:%M%P")
        %td
          - if post.twitter?
            = 'Twitter'
            %br
            = post.twitter_publish_date.strftime("%B %e, %Y %l:%M%P")
        %td= link_to 'Edit', edit_post_path(post)

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/import.html.haml
%h1 Import posts

= form_for :post, url: { action: "upload" } do |f|
  = f.file_field :excell

  = f.submit "Upload"

app/views/posts/index.html.haml
%h1 Bulk Scheduler

= render 'set_dates'

%table
  %thead
    %tr
      %th
      %th
      %th
      %th
      %th
      %th
      %th
  %tbody
    - i = 0
    - @posts.each do |post|
      - i += 1
      %tr
        %td= i
        %td= post.text
        %td= image_tag post.image(:thumb) unless post.image.blank?
        %td
        %td
          - if post.facebook?
            = 'Facebook'
            %br
            = post.facebook_publish_date.strftime("%B %e, %Y %l:%M%P")
        %td
          - if post.twitter?
            = 'Twitter'
            %br
            = post.twitter_publish_date.strftime("%B %e, %Y %l:%M%P")
        %td= link_to 'Edit', edit_post_path(post)

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/settings.html.haml
%h2 Social Media Integrations
%h3 Facebook
= link_to "Connect to Facebook", "/auth/facebook"
%h2 Facebook Profile

- if @user_facebook_oauth
  - @user_graph = Koala::Facebook::API.new(@user_facebook_oauth)
  - my_name =  @user_graph.get_object('me')

  = form_tag(settings_publish_token_path) do
    .row
      = my_name['name'] + "'s Facebook Profile"
      = radio_button_tag "facebook", "profile"
    %h2 Facebook Page
    - @user_graph.get_connections('me', 'accounts').each do |page|
      .row
        = page['name']
        = radio_button_tag "facebook", page['access_token']
    .row
      = submit_tag "Save changes"

%h3 Twitter
= link_to "Connect to Twitter", "/auth/twitter"

.personal_information
  = form_for @user do |f|
    .row
      = f.label :full_name
      = f.text_field :full_name
    .row
      = f.label :company_name
      = f.text_field :company_name

    .row
      = f.label :password
      = f.text_field :password
    .row
      = f.label :email
      = f.text_field :email
    .row
      = f.submit

%div
  Date joined
  = @user.created_at.strftime("%B %e, %Y")